---
dist: trusty
language: node_js
sudo: false
git:
  depth: 5

node_js: stable

env:
  - DOCKER_IMAGE=api
  - DOCKER_IMAGE=frontend

jobs:
  include:

  - stage: test
    script:
      - echo $DOCKER_IMAGE
  - services:
      - docker
    script:
      - echo $DOCKER_IMAGE

  - stage: build
    services:
      - docker
    script:
      - echo $DOCKER_IMAGE

jobs:
  include:
    - stage: deploy
      if: type = push AND branch = master
      env:
        - DOCKER_TAG=latest
      script: echo $DOCKER_IMAGE
