---
dist: trusty
language: node_js
sudo: false
git:
  depth: 5

node_js: stable

env:
  - DOCKER_IMAGE=api
  - DOCKER_IMAGE=frontend

jobs:
  include:

  - stage: push
    if: type = push AND branch = master
    services:
      - docker
    env:
      - DOCKER_TAG=latest
    script:
      - echo $DOCKER_IMAGE

jobs:
  include:
    - stage: deploy
      script: echo $DOCKER_IMAGE
