---
dist: trusty
language: node_js
sudo: false
git:
  depth: 5

node_js: stable

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.1
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:

  - stage: test
    env: DOCKER_IMAGE=frontend
    script:
      - cd @foo/$DOCKER_IMAGE
      - yarn test
  - #
    env: DOCKER_IMAGE=api
    script:
      - cd @foo/$DOCKER_IMAGE
      - yarn test

  - stage: build
    env:
      - DOCKER_IMAGE=api
      - DOCKER_IMAGE=frontend
    services:
      - docker
    script:
      - echo $DOCKER_IMAGE
      - docker -v

  - stage: deploy
    if: type = push AND branch = master
    env:
      - DOCKER_TAG=latest
    script: echo $DOCKER_IMAGE
