---
dist: trusty
language: node_js
sudo: false
git:
  depth: 5

node_js: stable

env:
  - DOCKER_IMAGE=api
  - DOCKER_IMAGE=frontend

jobs:
  include:

  - stage: test
    env: PACKAGE=frontend
    script:
      - cd @foo/$DOCKER_IMAGE
      - yarn test
  - #
    env: PACKAGE=api
    script:
      - cd @foo/$DOCKER_IMAGE
      - yarn test

  - stage: build
    services:
      - docker
    script:
      - echo $DOCKER_IMAGE
      - docker -v

  - stage: deploy
    if: type = push AND branch = master
    env:
      - DOCKER_TAG=latest
    script: echo $DOCKER_IMAGE
