dist: trusty
sudo: false
language: generic
git:
  depth: 5

services:
- docker

jobs:
  include:
  - stage: build docker image
    env:
    - REPO_SLUG=$(dirname $TRAVIS_REPO_SLUG)
    - DOCKER_IMAGE="$TRAVIS_REPO_SLUG:travis.$TRAVIS_BRANCH"
    - secure: yGUy4MZKzr7kgNBqea6z/WIlJvzdkimZGWJlK5cfSIORFRMOG56/QFo6YCdcvUC0k96B2RljNmFkFgaLgT6bAoiKRrMCIZeOokE8QG7J98s7rmMWqcN41Biiz1VR6rHdTXoR7El51jQeIURK9aDvJwOLGoAOg8GzkPbTR+OeSEli5k78OyzWB/cab8w2Q64VH+IWjyg0PFdtChSUgPMA1s3U0Y6GLEBCSQCpjmZ9IUSkub02RuVUbVhedFReyo8CVKZb5nevtPgu530oem4igQzndjHQierk64z25XZ06RI+5ZC7AsqHL5skgVaJQ8gfifywf+8tr4cJCMqpA5hXrKpwtj0ysD17fOVdw27xq1Xe9Hcac4P8213nvPt1KN4gWky9t11BrSmbO6niymoE1d19K6w5ctiB2uCDtI4JSExAKdYXRwga006rVr2D2OitkZZHHgFIo60MQ9v9KPlp7AFcmPLzVRNKraMsActb+TnIqNwv+0GIeXEWJJt2efONODIir5Pdmxm3VGxbeQi/msKdfbMZmN6Z5mcJ2uTqtRMS8pumZPaqm9MbB7vBLdO4cHntB3eSgBabrh7Y0c3tikhID17Ta9rETFbuV7QvNbhhywwm/R3p7iscJBLjT9sG8VaqqEHonfA37s9U40u7yyBpJ+6yxbHaU42/xpuz6tI=
    - secure: UtDOX64rLuhL842ThmJId2JFbRA/q4kzqWivWVPInQtV0Lnef6sb868SD9M+x2BikSa4lB6uPohL3sKu2+iryxZ7XQ+xv691cam54kjGi8kC6EmouwSKblz/CNps/dIOb3nK7yMzq7FhcSI1WGBJUFrUrerNE908llIQkgl8nTCldd8bBCWman0vUfEq1TgTXEdke5tYMm2oB7/B4938R6hnSU/0odeLgreQ2cQAqCGUGXmQf0o9HkI+8S1cnmrcCusg3hJcXJ2UeRdmUMk6Qv6EESAL00yu3ovRlwNFxpSwRFwz/r2QqNkGBFTkfL5u7owyCP9Sf4FpBdmjtCg0LA+GZcINdD0g1PMrFdlL+fYIAUzmwqubpREcOcDxmm2mPgl13M+gv5W0mwFhU2sy2kqBOLvDJqEJJ3ytzw7oe8lfdoqnjYEWKCr4AGKufi4cf7sN9JIoPIrAbWWa8HU+IoWbyxBUjCE5A5g74vpUdUiKwTDJtKcOmIkX2VPTIHrvFZlokiWMnrrE9lq6jL1UKwE9ld8wQj8BaLM2eHXBlazy/KXj8xw+QMEmwFibaptEo1yad1FwiPmdoOBLDjIaAFO6pFAvqw6lqh1MMR9qlAd9UYDa7cSezevb0PDHemaSRNlDLOFn/sLZkvmxBwb3AZiVgaYbNhqMP/ae7Kc7gWU=
    script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $REPO_SLUG:travis.$TRAVIS_BRANCH.${TRAVIS_COMMIT:0:7} .
      - docker images
      - docker push $REPO_SLUG:travis.$TRAVIS_BRANCH.${TRAVIS_COMMIT:0:7}
  - stage: test
    env: DOCKER_IMAGE="$TRAVIS_REPO_SLUG:travis.$TRAVIS_BRANCH.${TRAVIS_COMMIT:0:7}"
    script: docker run --rm $DOCKER_IMAGE yarn workspace @foo/frontend test
  - #
    env: DOCKER_IMAGE="$TRAVIS_REPO_SLUG:travis.$TRAVIS_BRANCH.${TRAVIS_COMMIT:0:7}"
    script: docker run --rm $DOCKER_IMAGE yarn workspace @foo/api test
  - stage: build
    env: DOCKER_IMAGE=api
    services:
    - docker
    script:
    - echo $DOCKER_IMAGE
    - docker -v
  - env: DOCKER_IMAGE=frontend
    services:
    - docker
    script:
    - echo $DOCKER_IMAGE
    - docker -v
  - stage: deploy
    if: type = push AND branch = master
    env:
    - DOCKER_TAG=latest
    script: echo $DOCKER_IMAGE
